### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by fabestah** [LrnzDC3696/hexapawn#3]

**Comment by SarveshPatil29** [comment]
Hi! I would like to work on this issue. Can you please assign it to me?

**Comment by constantinosgeorgiou** [comment]
Hello! Please assign this to me, my PR #4 is ready.

**Comment by fabestah** [comment]
I'm already working on it and nearly finished, sorry ✌️

**Comment by constantinosgeorgiou** [comment]
I understand. You could accept the PR and then add your own text at the specified places. I have structured it to be very straight forward.

**Comment by fabestah** [comment]
Yes, we can for sure combine them, you have some parts that I didn't include and the other way around plus I think they would fit together quite good 👍
Should I already include the parts of your version or do you want to create a separate PR and do it yourself?
In my version there are still missing emojis, some text needs to be expanded and the rest which is missing I would take from your version and adjust it so it fits to the rest, does that sound good to you? :)

**Comment by LrnzDC3696** [comment]
Done on #4 and #7
