### ISSUE TITLE
Add Contributor Covenant Code of Conduct

### ISSUE THREAD

**Issue by fabestah** [LrnzDC3696/hexapawn#8]
Add a CODE_OF_CONDUCT.md, which represents the values of this project, makes clear that everybody in the community gets treated with respect and that the participation in our community will always be a harassment-free experience for everyone.

**Comment by fabestah** [comment]
Could you please add the Hacktoberfest label again, I'm nearly done with it 😊👍

**Comment by LrnzDC3696** [comment]
What is cocecant?

**Comment by fabestah** [comment]
Typo 😅😂

**Comment by LrnzDC3696** [comment]
#10
